version: "2"
services:
  database:
    image: mysql:5.7
    ports:
      - "4306:3306"
    volumes:
      - ./docker-src/db-dump:/docker-entrypoint-initdb.d:cached
    environment:
      - MYSQL_ROOT_PASSWORD=somegloriouspassword
      - MYSQL_DATABASE=craft_cms
  server:
    image: netlifedesign/craft-starter-base
    ports:
      - "5000:80"
    volumes:
      - ./:/var/www/html/:cached
      - ./storage/:/var/www/html/storage/:delegated
    environment:
      - DATABASE_URL=mysql://root:somegloriouspassword@database:3306/craft_cms
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
      - REDIS_URL=redis://redis_service:6379
